#----------FORMULARIO----------
print("Formulario de usuarios")
nombre_uno = input("Ingrese su nombre número uno: ")
nombre_dos = input("Ingrese su nombre número dos: ")
apellido_uno = input("Ingrese su apellido número uno: ")
apellido_dos = input("Ingrese su apellido número dos: ")
#----------DATOS NUMERICOS----------
edad = int(input("Ingrese sus edad: "))
peso = float(input("Ingrese su peso: "))
telefono = int(input("Ingrese su número de telefono: "))
altura = float(input("Ingrese su altura: "))
cant_hijos = int(input("Ingrese el número de hijos que tiene: "))
año_nacimiento = int(input("Ingrese su año de nacimiento: "))
mes_nacimiento = int(input("Ingrese su mes de nacimiento: "))
dia_nacimiento = int(input("Ingrese su día de nacimiento: "))
cedula = int(input("Ingrese su numero de cédula (sin decimales ni espacios): "))
#----------DATOS DE TEXTO----------
correo = input("Ingrese su correo: ")
RH = input("Ingrese su tipo de sangre: ")
genero = input("Ingrese su genero: ")
estado_civil = input("Ingrese su estado civil: ")
eps = input("Ingreses su EPS: ")
universidad = input("Ingreses su universidad: ")
carrera = input("Ingreses su carrera: ")

print("Su nombre completo es:", nombre_uno.title(),nombre_dos.title(),apellido_uno.title(),apellido_dos.title())
print("Su edad es: ", edad,"años")
print("Su peso es:", peso, "Kg")
print("Su número de telefono es:",telefono)
print("Su altura es: ",altura)
print("Su cantidad de hijos es:",cant_hijos)
print("Su fecha de nacimiento es :",dia_nacimiento,"/",mes_nacimiento,"/",año_nacimiento)
print("Su número de cedula es: ",cedula)
print("Su correo electronico es: ",correo)
print("Su RH es: ",RH)
print("Su genero es: ",genero)
print("Su estado civil es: ",estado_civil)
print("Su EPS es:",eps)
print("Su universidad es: ",universidad)
print("Su carrera es: ",carrera)